### ISSUE TITLE
Incorrect data field used.

### ISSUE THREAD

**Issue by cyberLaVoy** [dsu-effectiveness/ushe_student_file_submission#2]
https://github.com/dsu-effectiveness/ushe_student_file_submission/blob/57db490754bf0d6ac71d3cadbf078803f92d6591/sql/student_file_with_versioning.sql#L5

This line needs to be replaced with the following:

```sql
b.ssid AS student_ssid,
```

**Comment by cdemkegit** [comment]
made the change in the sql so that we can pull in ssid.
